version: '3.8'

services:
  ytdl-sync:
    image: drwahl/ytdl-sync:latest
    container_name: ytdl_sync
    restart: unless-stopped
    environment:
      - YTDL_URL=http://ytdl-material:17442
      - PLEX_URL=http://plex-server:32400
      - PLEX_TOKEN=YOUR_PLEX_TOKEN_HERE
      - PLEX_MUSIC_SECTION_ID=1
      - LOCAL_DOWNLOAD_DIR=/music
      - LOG_PATH=/logs/ytdl_sync.log
      - LOCK_FILE_PATH=/tmp/ytdl_sync.lock
    volumes:
      - /path/to/local/music:/music:rw
      #- /tmp:/tmp:rw  # Used for the lock file. Only needed if multiple containers might run
      #- /path/to/local/logs:/logs:rw
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Uncomment below if you want to run this as a cron job inside the container (example runs every hour)
    # command: ["sh", "-c", "while true; do python /app/sync.py; sleep 3600; done"]
