version: "3.9"
services:
  ytdl_sync:
    build: .
    container_name: ytdl_sync
    restart: unless-stopped
    environment:
      # YTDL-material config
      - YTDL_URL=http://ytdl.example.com
      - YTDL_USERNAME=username
      - YTDL_PASSWORD=password

      # Plex config
      - PLEX_URL=http://plex.local:32400
      - PLEX_TOKEN=your_plex_token
      - PLEX_MUSIC_SECTION_ID=1

      # Local download dir inside container
      - LOCAL_DOWNLOAD_DIR=/music

      # Optional: log file path inside container, comment out to disable file logging
      # - LOG_PATH=/logs/ytdl_sync.log

      # Lock file path (can stay default or customize)
      - LOCK_FILE_PATH=/tmp/ytdl_sync.lock

    volumes:
      # Mount your music library directory here
      - /path/on/host/music:/music:rw

      # Optional: mount a logs directory if LOG_PATH is set
      # - /path/on/host/logs:/logs:rw

    # Run once daily via external cron, or schedule here with restart: unless-stopped

