version: "3.9"
services:
  ytdl_sync:
    build: .
    container_name: ytdl_sync
    restart: unless-stopped
    environment:
      YTDL_URL: http://ytdl.example.com
      YTDL_USER: user
      YTDL_PASSWORD: pass
      YTDL_API_KEY: keykeykey

      PLEX_URL: http://plex.local:32400
      PLEX_TOKEN: your_plex_token
      PLEX_MUSIC_SECTION_ID: "1"

      DOWNLOAD_DIR: /music

      # Optional: enable log file path inside container (comment out to disable)
      # LOG_PATH: /logs/ytdl_sync.log

      LOCK_FILE: /tmp/ytdl_sync.lock

    volumes:
      # Mount your music library directory here
      - /path/on/host/music:/music:rw

      # Optional: mount a logs directory if LOG_PATH is set
      # - /path/on/host/logs:/logs:rw

    # Run once daily via external cron, or schedule here with restart: unless-stopped

